pt-boop/uptodate-manga-image-translator

manga_translator/translators/groq.py
Update groq.py proper names modif fix
=> Update groq.py proper names modif fix

manga_translator/translators/groq.py
=> Update groq.py propernames modif fix

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#9
=> Revert "Update groq.py propernames modif fix"

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#8
=> Revert "Update groq.py proper names modif fix"

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#13
=> Revert "Revert "Update groq.py proper names modif fix""

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#12
=> Revert "Revert "Update groq.py propernames modif fix""

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#15
=> Revert "Revert "Revert "Update groq.py propernames modif fix"""

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#14
=> Revert "Revert "Revert "Update groq.py proper names modif fix"""

manga_translator/translators/groq.py
Update groq.py propernames to source text
=> Update groq.py propernames to source text

manga_translator/translators/groq.py
Update groq.py reduct personal pronoun correction
=> Update groq.py reduct personal pronoun correction

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#22
=> Revert "Update groq.py zero temperature"

manga_translator/translators/groq.py
Update groq.py loosen to temp 0.4
=> Update groq.py loosen to temp 0.4

manga_translator/translators/groq.py
Update groq.py reducted mythological terms
=> Update groq.py reducted mythological terms

manga_translator/translators/groq.py
Update groq.py temp 0.3 topp 0.8
=> Update groq.py temp 0.3 topp 0.8

manga_translator/translators/groq.py
=> Update groq.py topp back 0.95

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#28
=> Revert "Update groq.py topp back 0.95"

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#27
=> Revert "Update groq.py temp 0.3 topp 0.8"

manga_translator/translators/groq.py
Update groq.py temp and topp up 1
=> Update groq.py temp and topp up 1

manga_translator/translators/keys.py
Update keys.py change to new scout
=> Update keys.py change to new scout

manga_translator/translators/groq.py
Update groq.py set 0 temp and topp 1
=> Update groq.py set 0 temp and topp 1

manga_translator/translators/groq.py
=> Update groq.py adjust topp

manga_translator/translators/groq.py
Update groq.py set guardrails for stray commentaries
=> Update groq.py set guardrails for stray commentaries

manga_translator/translators/groq.py
Update groq.py increased temp for more freedom
=> Update groq.py increased temp for more freedom

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#39
=> Revert "Update groq.py increased temp for more freedom"

manga_translator/translators/groq.py
Update groq.py change to another guadrails
=> Update groq.py change to another guadrails

manga_translator/translators/groq.py
Update groq.py overhaul async translation to address issue
=> Update groq.py overhaul async translation to address issue

manga_translator/translators/groq.py
Update groq.py overhaul 4 last hitted my limit
=> Update groq.py overhaul 4 last hitted my limit

manga_translator/translators/groq.py
Update groq.py testing fidelity
=> Update groq.py testing fidelity

manga_translator/translators/groq.py
Update groq.py reduce freedom temp change
=> Update groq.py reduce freedom temp change

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#47
=> Revert "Update groq.py reduce freedom temp change"

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#46
=> Revert "Update groq.py testing fidelity"

manga_translator/translators/groq.py
=> Update groq.py slight freedom

manga_translator/translators/keys.py
Update keys.py change to llama4 maverick
=> Update keys.py change to llama4 maverick

manga_translator/translators/keys.py
=> Update keys.py back to scount

manga_translator/translators/keys.py
=> Update keys.py new model

manga_translator/translators/groq.py
Update groq.py temp 0.2 topp 0.95
=> Update groq.py temp 0.2 topp 0.95

manga_translator/translators/keys.py
=> Update keys.py to maverick

manga_translator/translators/keys.py
Reverts pt-boop/uptodate-manga-image-translator#61
=> Revert "Update keys.py to maverick"

manga_translator/translators/groq.py
Update groq.py hyper focus deepseek
=> Update groq.py hyper focus deepseek

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#64
=> Revert "Update groq.py hyper focus deepseek"

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#65
=> Revert "Revert "Update groq.py hyper focus deepseek""

manga_translator/translators/groq.py
Update groq.py revert normal depr1distill70b temp and topp
=> Update groq.py revert normal depr1distill70b temp and topp

manga_translator/translators/groq.py
Update groq.py fix truncation issue
=> Update groq.py fix truncation issue

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#68 - made worse
=> Revert "Update groq.py fix truncation issue"

manga_translator/translators/groq.py
Update groq.py bootleg fix for truncation issue
=> Update groq.py bootleg fix for truncation issue

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#70
=> Revert "Update groq.py bootleg fix for truncation issue"

manga_translator/translators/keys.py
Reverts pt-boop/uptodate-manga-image-translator#73
=> Revert "Update keys.py change to llama maverick"

manga_translator/translators/keys.py
Reverts pt-boop/uptodate-manga-image-translator#72
=> Revert "Update keys.py test llama scout"

manga_translator/translators/groq.py
Update groq.py added this engine
=> Update groq.py added this engine

manga_translator/translators/groq.py
Update groq.py chatgpt overhauld
=> Update groq.py chatgpt overhauld

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#78
=> Revert "Update groq.py  Stop Sequences"

manga_translator/translators/keys.py
=> Update keys.py llama scout

manga_translator/translators/keys.py
=> Update keys.py llama maverick

manga_translator/translators/keys.py
Reverts pt-boop/uptodate-manga-image-translator#82
=> Revert "Update keys.py llama maverick"

manga_translator/translators/keys.py
Reverts pt-boop/uptodate-manga-image-translator#81
=> Revert "Update keys.py llama scout"

manga_translator/translators/keys.py
Reverts pt-boop/uptodate-manga-image-translator#85
=> Revert "Update keys.py change to scout"

manga_translator/translators/keys.py
Update keys.py to metallama maverick
=> Update keys.py to metallama maverick

manga_translator/translators/keys.py
Reverts pt-boop/uptodate-manga-image-translator#87
=> Revert "Update keys.py to metallama maverick"

manga_translator/translators/groq.py
Update groq.py combined templateA.B overhauld
=> Update groq.py combined templateA.B overhauld

manga_translator/translators/groq.py
Update groq.py combined templateA.B overhauld improve with code fix
=> Update groq.py combined templateA.B overhauld improve with code fix

manga_translator/translators/groq.py
Update groq.py combined templateA.B overhauld improve with code fix 2
=> Update groq.py combined templateA.B overhauld improve with code fix 2

manga_translator/translators/groq.py
Update groq.py tuple fix to chat system template
=> Update groq.py tuple fix to chat system template

manga_translator/translators/groq.py
Update groq.py making cst uncensored
=> Update groq.py making cst uncensored

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#94
=> Revert "Update groq.py overhauld 2"

manga_translator/translators/groq.py
Update groq.py complete base recode
=> Update groq.py complete base recode

manga_translator/translators/groq.py
Update groq.py complete base recode2
=> Update groq.py complete base recode2

manga_translator/translators/groq.py
Update groq.py complete base recode3
=> Update groq.py complete base recode3

manga_translator/translators/groq.py
Update groq.py complete base recode4
=> Update groq.py complete base recode4

manga_translator/translators/groq.py
Update groq.py complete base recode4.3 indent
=> Update groq.py complete base recode4.3 indent

manga_translator/translators/groq.py
Update groq.py complete base newcode
=> Update groq.py complete base newcode

manga_translator/translators/groq.py
Update groq.py cst and sample from newcode
=> Update groq.py cst and sample from newcode

manga_translator/translators/groq.py
Update groq.py complete newcode2
=> Update groq.py complete newcode2

manga_translator/translators/groq.py
Update groq.py complete newcode3
=> Update groq.py complete newcode3

manga_translator/translators/groq.py
Update groq.py complete newcode4
=> Update groq.py complete newcode4

manga_translator/translators/groq.py
Update groq.py complete newbined code
=> Update groq.py complete newbined code

manga_translator/translators/groq.py
Update groq.py complete newbined code2
=> Update groq.py complete newbined code2

manga_translator/translators/groq.py
Update groq.py replace by json data
=> Update groq.py replace by json data

manga_translator/translators/groq.py
Update groq.py replace by json data2
=> Update groq.py replace by json data2

manga_translator/translators/groq.py
Update groq.py replace by json data4
=> Update groq.py replace by json data4

manga_translator/translators/groq.py
Update groq.py fix slang and ambigous
=> Update groq.py fix slang and ambigous

manga_translator/translators/groq.py
Reverts pt-boop/uptodate-manga-image-translator#117
=> Revert "Update groq.py fix slang and ambigous"

manga_translator/config.py, manga_translator/detection/default.py, manga_translator/manga_translator.py, manga_translator/rendering/__init__.py, manga_translator/rendering/text_render_pillow_eng.py
new text render and apply detect-20241225.ckpt #972 from qwopqwop200
=> new text render and apply detect-20241225.ckpt #972

manga_translator/config.py, manga_translator/ocr/model_32px.py, manga_translator/ocr/model_48px.py, manga_translator/ocr/model_48px_ctc.py, manga_translator/translators/__init__.py, manga_translator/translators/gemini_2stage.py, manga_translator/translators/keys.py
Gemini 2 stage: add gemini 2 stage translator and add config ocr valid prob #973 from qwopqwop200
=> Gemini 2 stage: add gemini 2 stage translator and add config ocr valid prob #973
